name: ci

on:
  schedule:
    - cron: 0 0 * * * # daily at midnight

  workflow_dispatch: # or manually dispatch the job
    inputs:
      hedgehog-tests:
        description: argument for --hedgehog-tests
        required: false
        default: "100000"

env: 
  HEDGEHOG_TESTS: ${{ github.event.inputs.hedgehog-tests || 100000 }}

jobs:
  nightly-testsuite:
    name: "🌘 Nightly Test Suite"
    runs-on: [self-hosted, plutus-benchmark]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Run Plutus Core Test
        run: | 
          pushd plutus-core
          nix run --no-warn-dirty --accept-flake-config .#plutus-core-test -- --hedgehog-tests $HEDGEHOG_TESTS
          popd

      - name: Run Plutus IR Test
        run: |
          pushd plutus-core
          nix run --no-warn-dirty --accept-flake-config .#plutus-ir-test -- --hedgehog-tests $HEDGEHOG_TESTS
          popd
